
ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS kpp text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS ogrn text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS legal_address text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bank_name text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bank_bik text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bank_account text DEFAULT NULL,
ADD COLUMN IF NOT EXISTS bank_corr_account text DEFAULT NULL;
